### ISSUE TITLE
update ODPS feed

### ISSUE THREAD

**Issue by marisademeglio** [daisy/epub-accessibility-tests#109]
This is no longer current:
https://github.com/daisy/epub-accessibility-tests/blob/main/feeds/opds.json

The official test book downloads live on epubtest.org; I removed the `build` directory from our version control because it can easily be overwritten with non-official versions while the books are being developed.

The official downloads could instead live only on github, that would be fine too, if we setup a release-based workflow that tags the repo and builds the epubs and updates the ODPS feed automatically. However, there could be cases where individual books get updated at different times throughout the year, so the whole repo would not necessarily be released at the same time.

Probably a monorepo setup would work but as everyone is comfortable with what we have now, I'm hesitant to change it or make it overly complicated.

cc @gautierchomel do you have any ideas here?

**Comment by gautierchomel** [comment]
I've been confused while version on the repo are not the same as the one found on the site. 

So yes, I would preferably have a clear view of source files and releases at the same place. 

I see a use for continuous built so we can have up-to-date built for the individuals updates and the "being developed".

**Comment by marisademeglio** [comment]
I am moving all the releases to github releases. It's not a perfect fit as I mentioned above about updates coming throughout the year for different books but there are upsides, one download location only and corresponding repo tagging. 

The initial few releases are here:
https://github.com/daisy/epub-accessibility-tests/releases

I will add more as the new books get ingested.

If I could automate an ODPS feed, what would you put on it? The latest versions of the test books? All the versions?

**Comment by gautierchomel** [comment]
Nice move. 
I think that the last version is sufficient and less confusing unless there is a need to perform older version tests.

**Comment by marisademeglio** [comment]
Will update this feed with the latest releases later in the week. All releases are currently on GH.

**Comment by marisademeglio** [comment]
I wrote a script that generates an OPDS feed from the latest book versions in this repo. A sample output file from the script is here:
https://github.com/daisy/epub-accessibility-tests/blob/main/feeds/opds-test.json

@gautierchomel could you have a look at it? The output was based on the file you created with some improvements for image URLs as well as using dc:identifier directly instead of making a new string with the book title etc. 

I don't know the best way to test these files out. I tried both OPDS in Thorium:
- https://raw.githubusercontent.com/daisy/epub-accessibility-tests/main/feeds/opds-test.json
- https://raw.githubusercontent.com/daisy/epub-accessibility-tests/main/feeds/opds.json

but neither works there.

**Comment by gautierchomel** [comment]
That's because of http headers. This will work: 

- https://rawcdn.githack.com/daisy/epub-accessibility-tests/6b92441854a97d61ef1563bd7388203906b5cb66/feeds/opds.json
- opds://rawcdn.githack.com/daisy/epub-accessibility-tests/6b92441854a97d61ef1563bd7388203906b5cb66/feeds/opds.json

**Comment by marisademeglio** [comment]
Oh great, then the new one is working after all:
https://rawcdn.githack.com/daisy/epub-accessibility-tests/main/feeds/opds-test.json

The image links use raw.githubusercontent.com and they load ok (except for the media overlays book which has no cover image).

I am going to replace the current odps.json file with this new one.
