### ISSUE TITLE
Revise scope of read aloud test

### ISSUE THREAD

**Issue by ways2read** [daisy/epub-accessibility-tests#111]
At the start of the read aloud test it says:

> The tests given below are for evaluating the Read Aloud feature within the reading system. Do not perform these reading tests using a screen reader or an Operating System feature or a third party tool.

The capabilities of browsers and operating systems features have improved and offer a useful solution for some users in some situations. We have been evaluating browser-based reading systems using the browser's read aloud in evaluations for a couple of years. Propose to amend this test to read:

> The tests given below can be conducted using a Read Aloud feature offered within the reading system, web browser, a third-party tool,  or via an Operating System feature. Do not perform these reading tests using a screen reader designed for blind users.

**Comment by prashantverma2014** [comment]
I think this change is needed. 

 

From: Richard Orme ***@***.***> 
Sent: Thursday, February 15, 2024 7:07 PM
To: daisy/epub-accessibility-tests ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [daisy/epub-accessibility-tests] Revise scope of read aloud test (Issue #111)

 

At the start of the read aloud test it says:

The tests given below are for evaluating the Read Aloud feature within the reading system. Do not perform these reading tests using a screen reader or an Operating System feature or a third party tool.

The capabilities of browsers and operating systems features have improved and offer a useful solution for some users in some situations. We have been evaluating browser-based reading systems using the browser's read aloud in evaluations for a couple of years. Propose to amend this test to read:

The tests given below can be conducted using a Read Aloud feature offered within the reading system, web browser, a third-party tool, or via an Operating System feature. Do not perform these reading tests using a screen reader designed for blind users.

**Comment by GeorgeKerscher** [comment]
Good change./G

**Comment by ways2read** [comment]
I made this change and submitted a PR
