### ISSUE TITLE
Items that have changed needs to be provided to Marisa

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#119]
Avneesh, George, Charles and Richard should put a comment in this issue that details the issues that have changed and require retesting. Provide the book and test number.

**Comment by GeorgeKerscher** [comment]
The non-visual test book has several new tests. However, the old tests have not changed, i.e. there is no need to retest.

**Comment by avneeshsingh** [comment]
In epub30-test-0301, the changes were descriptive, without changing fundamental tests. The following tests were updated.
anno-110 Review and navigate Bookmarks or Highlights
anno-310 Review and navigate Notes
nav-110 Navigate content by pages

**Comment by marisademeglio** [comment]
So far I see:

1. 301 (fundamental): no changed tests that would require retesting
2. 302 (non-visual): no changed tests that would require retesting
3. 303 (visual adjustments): suspect no changed tests that would require retesting, pending answer for 710
4. 304 (read aloud): suspect no changed tests that would require retesting, @ways2read can you confirm?

**Comment by clapierre** [comment]
Test 710 change of SVG image, I think does qualify as we combined a couple tests and changed the image so I think it would.
We removed test 610 and combined both into 710 with a better SVG image so I think it qualifies for a retest.

**Comment by ways2read** [comment]
Regarding 303 (visual adjustments): test 610 was redundant so was removed. Test 710 was improved with an image that makes testing easier and more meaningful. I believe the test results for 710 would be exactly the same whether the SVG image is a gray circle or a flower.

**Comment by ways2read** [comment]
Regarding 304 (read aloud):
## Changed tests
None
## Tests that were removed
ReadAloud-710 The emphasis or highlight colour can be changed
## New tests
ReadAloud-350 Image alternate text reading
ReadAloud-410 Change Read Aloud reading speed

**Comment by marisademeglio** [comment]
Note from the call, visual adjustments 710 will not be counted as changed
