### ISSUE TITLE
Change the image used in visual-610 support for SVG

### ISSUE THREAD

**Issue by ways2read** [daisy/epub-accessibility-tests#12]
When evaluating the SVG support and SVG enlargement, the grey circle used in the current test book is rather simplistic and not interesting when conducting the evaluation with test subjects. Suggest replacing with a more interesting and visually complex image. There is a public domain image of a tree kangaroo that is a possibility, now stored on the DAISY Dropbox in the epubtest folder. Of courses, there are many other possibilities.

**Comment by marisademeglio** [comment]
Triggers retesting if the filename is different and/or if the associated description changes.

**Comment by ways2read** [comment]
Richard will send the image to @ways2read
