### ISSUE TITLE
Text in nave doc same as targeted heading

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#13]
The text on the nave doc and the TOC needs to align with the text in the target headings. Right now the text is different and makes it confusing for the testers.

**Comment by avneeshsingh** [comment]
Indeed, headings in content document should match entries in TOC to the extent possible. We may like to have some scope of adjustments, because contextual information is not available in TOC.

**Comment by prashantverma2014** [comment]
The actual heading can sometimes be very long and may not be appropriate to be included in the TOC as is. Therefore, smaller text with similar meaning should be acceptable.

**Comment by avneeshsingh** [comment]
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/daisy/epub-accessibility-tests/issues/13#issuecomment-402052860",
"url": "https://github.com/daisy/epub-accessibility-tests/issues/13#issuecomment-402052860",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [daisy/epub-accessibility-tests] Text in nave doc same as targeted heading (#13)",
"sections": [
{
"text": "",
"activityTitle": "**prashantverma2014**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@prashantverma2014",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"daisy/epub-accessibility-tests\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"daisy/epub-accessibility-tests\",\n\"issueId\": 13\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/daisy/epub-accessibility-tests/issues/13#issuecomment-402052860"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 330151899\n}"
}
],
"themeColor": "26292E"
}
]
