### ISSUE TITLE
Align outcome terminology in test books and on website

### ISSUE THREAD

**Issue by ways2read** [daisy/epub-accessibility-tests#17]
The test books ask that the tests are marked "Pass" or "Fail". The website provides the options "Supported" and "Not supported". The test books or the website terminology could be changed to bring them into alignment.

I think this is not high priority.

**Comment by marisademeglio** [comment]
Agreed. The pain point here is that any wording changes trigger retesting flags. I also wonder if we need to have that text in the book at all ... it's more appropriate on the site itself, I'd think, since that's where you're filling out a form.

**Comment by GeorgeKerscher** [comment]
I believe this has been resolved with titles revised in early 2024.
