### ISSUE TITLE
Increase padding of focused Boarder around Test

### ISSUE THREAD

**Issue by clapierre** [daisy/epub-accessibility-tests#29]
Currently on the left/right side of the box board around the current Test we have 1 pixel between the boarder and the text inside.
Please increase this to at lease 3-5 pixels to make it easier to read the content inside the box.

**Comment by marisademeglio** [comment]
Was this for a particular book? Or all the books? Feel free to submit a PR.

**Comment by GeorgeKerscher** [comment]
I believe this was resolved.
