### ISSUE TITLE
More navigation features in 0300?

### ISSUE THREAD

**Issue by murata2makoto** [daisy/epub-accessibility-tests#3]
In Keio Advanced Publishing Lab, we are studying test documents from this repository.   We created a [fork ](https://github.com/Advanced-Publishing-Laboratory/epub-accessibility-tests) and translated epub30-test-0300.

Navigation features of DAISY players appear to be far beyond those of commercial EPUB RSs today.  "Navigate to previous/next section" is an example.  It is in EPUBTEST 0320 but not in  EPUBTEST 0300.  But 0320 is dedicated to MO.  Should 0300 or a separate test document cover more navigation features?

**Comment by marisademeglio** [comment]
0300 has a section called "Navigation Tests", including locating specific sections, but you're right, there's no "previous/next section" test.

For 0320 (MO), it is good to have a simple navigation test to make sure that playback isn't interrupted while a user navigates, but we didn't want to duplicate too much from 0300.

Anything to add, @prashantverma2014 @avneeshsingh ?

**Comment by avneeshsingh** [comment]
Yes, the intention was to reduce duplicate tests. I can review the tests in light of Makoto’s comments and bring the topic to reading systems call on 22nd November.

**Comment by murata0204** [comment]
Since an EPUB publication may consists of multiple HTML content documents, should we separate structural navigation within a single HTML content document and that across multiple HTML content documents?

**Comment by avneeshsingh** [comment]
I have gone through the tests design again. Most of the good points highlighted by Makoto are already covered in the test books. The details are as follows:

Topic 1: Separation of navigation in the same file vs navigation across the whole publication:
In the fundamental test book, under basic tests we have
"[REQUIRED]nav-010
Navigate to chapters through the Table of Contents."

This is for navigation across the whole publication. 
And in non-visual reading, we have the following:
"[REQUIRED]reading-1210
Navigate the content by headings. 
Check if you can move to the next and previous headings in this book without using the Table of Contents."

This test is for navigation with in the same file.

Topic 2: The Media Overlays has test for move to next/previous section but the fundamental test book does not have the same:
In fundamental test book, in non-visual reading we have

"[REQUIRED]reading-1210
Navigate the content by headings. 
Check if you can move to the next and previous headings in this book without using the Table of Contents."

This is equivalent to the following in the Media Overlays test book:
"[FUNDAMENTAL]MOA-NAV-020 Navigate to previous section 
Tests whether navigation to previous section is supported."

"[FUNDAMENTAL]MOA-NAV-030 Navigate to next section 
Tests whether navigation to next section is supported."

I hope this clarifies. In case this does not address the requirements, we are open to suggestions for improving the test books. We also have this topic scheduled in the reading systems call today.

**Comment by murata0204** [comment]
> Topic 1: Separation of navigation in the same file vs navigation across the whole publication:
> In the fundamental test book, under basic tests we have
> "[REQUIRED]nav-010
> Navigate to chapters through the Table of Contents."
> 
> This is for navigation across the whole publication.

But this requires the user to visit the TOC.  One blind guy in Japan believes 
that we need structural nav without visiting the TOC as well as that via the 
TOC.

**Comment by murata0204** [comment]
> And in non-visual reading, we have the following:
> "[REQUIRED]reading-1210
> Navigate the content by headings.
> Check if you can move to the next and previous headings in this book without using the Table of Contents."
> 
> This test is for navigation with in the same file.

Suppose that that the current position is a clause in an HTML.
Shouldn't it be possible to move to the next clause, which 
is contained in the next HTML ?

**Comment by murata0204** [comment]
In my understanding,  A11Y features of DAISY readers are richer than those of commercial EPUB readers.  Are we trying to create a test item for each feature of major DAISY readers?  Or, are we trying to cover basic features so that commercial EPUB readers will become more reasonable?

**Comment by murata0204** [comment]
Another question.   Do we need sentence-based navigation?

**Comment by GeorgeKerscher** [comment]
That is normally provided by the screen reader. I do not think we need that in the RS testing.
 
 
BestG
Eorge

**Comment by avneeshsingh** [comment]
One test that we should definitely add based on this discussion is #6. # # #

**Comment by GeorgeKerscher** [comment]
What test exactly are we proposing to add?

**Comment by ways2read** [comment]
Closed in the reading system call November 14
