### ISSUE TITLE
Text: (graphic / image / img) inconsistency in results page

### ISSUE THREAD

**Issue by clapierre** [daisy/epub-accessibility-tests#32]
Minor point but in the extended image description tests the Test name sometimes has “img” and in others it says “image”, and still other have "graphic"

Which is showing up in epubtest.org table.
Detection of aria-details on **img** in figure
Moving to extended description next to the **image**
Block-level **image** with empty alt and without role="presentation"
Inline **graphic** with empty alt and without role="presentation"

etc...

Should we just use "image" everywhere?

**Comment by GeorgeKerscher** [comment]
I think we should use image everywhere. This should be fixed in all titles in the 2023 revision.

**Comment by GeorgeKerscher** [comment]
I believe this has been resolved.
