### ISSUE TITLE
Footnotes test

### ISSUE THREAD

**Issue by marisademeglio** [daisy/epub-accessibility-tests#47]
We may consider having a test of footnotes that demonstrates both using `<aside>` and using a generic element like `<div>` to contain the footnote.

If you look at the comments [in this issue](https://github.com/daisy/ace/issues/300), it seems that some reading systems implement footnotes well if they are in an `<aside>`, and otherwise not that well. 

This may affect accessibility if the footnote semantic is not being recognized solely from epub:type or role.

**Comment by GeorgeKerscher** [comment]
Closingd because it was added to Non-visual reading version 2
