### ISSUE TITLE
Add some text with which to evaluate read aloud pauses

### ISSUE THREAD

**Issue by ways2read** [daisy/epub-accessibility-tests#5]
ReadAloud-510 is a test for "Text to Speech handles punctuations and document structure appropriately."

When Read Aloud is activated, there should be slight pauses after headings, paragraphs, list items etc., rather than to read as if it is one continuous section of text.

There is currently no obvious text with which to check this in the test book. It could be something like:
“This is a regular sentence that includes nouns, verbs, adjectives and some punctuation.  A pause should indicate the start of a new sentence.
It should be possible to tell that this text is in a new paragraph.”

The when the test is being conducted, the read aloud feature can be used on this text. It can be used to check whether that there is a pause to indicate the presence of a comma and period. And also to check that the pause between paragraphs is longer than that between sentences.

**Comment by avneeshsingh** [comment]
Is this test supported well? Want to make sure that it is right fit for fundamental test book.

**Comment by ways2read** [comment]
Most reading systems read aloud supports punctuation and document structure ok. Where it fails is sometimes with a heading or list item that has no period at the end, which is really horrible.

I will propose some text that has been tested in some reading systems to ensure we don't set an impossible bar.
