### ISSUE TITLE
Create a RS test for ease of navigation in the TOC

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#53]
Many larger titles, especially in higher education textbooks can have huge table of contents. It can be difficult to navigate these titles. The RS should provide an easy way to navigate these large TOC. we should create a test title that has hundreds of entries and amake sure the RS has an easy way to quickly move through the table of contents.

**Comment by avneeshsingh** [comment]
This is stepping into performance testing.
We need to decide if we want to step beyond our current scope.

**Comment by ways2read** [comment]
This is a refinement of the test nav-005 in the Basic Functionality test book.

**Comment by GeorgeKerscher** [comment]
This is closed as a duplicate of 84.

**Comment by GeorgeKerscher** [comment]
Duplicate of 84.
