### ISSUE TITLE
Insert ISBN metadata to all test books

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#57]
We have been given the use of ISBN numbers from the Taylor & Francis Group. Thank you James for getting them for us. Next time the titles are updated, we should add the ISBN numbers.

**Comment by marisademeglio** [comment]
Do you have the ISBN numbers? I can add them.

**Comment by marisademeglio** [comment]
What is the preferred way to add an ISBN to an EPUB? I can think of a few approaches:

In addition to the publication identifier, we can add an ISBN identifier:
```
<dc:identifier id="uid">com.github.epub-testsuite.epub30-test-0302</dc:identifier>
<dc:identifier id="isbn">9781003410119</dc:identifier>
```

We can also add a refinement for that dc:identifier element, to say that it's an ISBN string:
```
<meta refines="#isbn" property="type (TODO)">ISBN</meta>
```
I don't know the actual property value that should be used though.

I have also seen just prefixing the ISBN number with `urn:ISBN:...` or `ISBN:...`, so then you could just do this
```
<dc:identifier id="isbn">9781003410119</dc:identifier>
```

 with no `<meta refines...>`. 

And, just for having more options (!), I see that Schema.org has an ISBN property, not sure where or if it's in use:
https://schema.org/isbn


@mattgarrish do you think any of these look like the right way?

**Comment by mattgarrish** [comment]
The specification non-normatively recommends using URIs for the identifiers, so you'll find the urn approach throughout the specification. That's generally how I've seen it done elsewhere.

The spec also shows [how to use onix:codelist5 with the value 15](https://www.w3.org/TR/epub-33/#example-using-values-from-a-scheme) in a number of examples to cover the refines approach, but reading systems generally ignore refinement properties so I doubt it does anything but add extra metadata.

**Comment by marisademeglio** [comment]
Suggested on the call
```
<dc:identifier id="isbn-id">9781000850512</dc:identifier>
<meta refines="#isbn-id" property="identifier-type" scheme="onix:codelist5">15</meta>
```

**Comment by marisademeglio** [comment]
Added to all books except Math + Extended descriptions
8ab8a0913f3d166d4c327c451e65ceac63530814

**Comment by marisademeglio** [comment]
which ISBN went where is noted in our Readme: https://github.com/daisy/epub-accessibility-tests?tab=readme-ov-file#index-of-materials
