### ISSUE TITLE
Testbooks should pass EPUBcheck 5.0

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#63]
When we update our EPUB test titles, they should pass the latest version of EPUBcheck.

**Comment by marisademeglio** [comment]
As far as I can tell, we just have to remove the Nav document from the spine (or have it there intentionally). Do we have any tests related to (or affected by) whether the Nav doc is in the spine or not?

**Comment by GeorgeKerscher** [comment]
Hi,

 

IMO we do not need or want the navdoc in the spine.

 

Best

George
