### ISSUE TITLE
Footnote Reading and Navigation needs to be tested

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#66]
Our test books do not yet have a test for the reading and navigation of footnotes. Some Reading Systems have a popup  and we do not know if this is accessible. The suggestion was the popup approach may be an alternative for extended descriptions as well, and the testing of the footnote approach would help us in this analysis.

**Comment by avneeshsingh** [comment]
We should keep our focus on accessibility and keep away from defining the user interface for reading systems. Our main focus for this test should be on.
* Assistive technology is able to detect the reference to the footnote and reach to the contents of the footnote.
* Assistive technology is able to read the content of the footnote.
* It provides mechanism to move back to original reading position from the footnote.

**Comment by ways2read** [comment]
In the reading systems call we identified that we should have tests for footnotes both with and without backlinks.

**Comment by GeorgeKerscher** [comment]
non-visual book, it requires more discussion, may be there will be multiple tests such as one with epubtype=footnote and one without. Also discuss Doc-footnote

**Comment by GeorgeKerscher** [comment]
On the call, we noted that publishers  are inserting backlinks, so we should use this technique. We have also added a backlink test in the experimental list for next year.

It would not be a criteria for passing, but it would be good to get information if it was announced that this is a footnote and if the Reading System provided a mechanism to go back without using the backlink. This could be suggested to add to the notes.

**Comment by GeorgeKerscher** [comment]
In this comment is the footnote text I have proposed. I have the noteref pointing to an aside. The footnote is in an aside and has a backlink to the reference. I use a superscript in the reference. I put the backlink into a separate paragraph after the footnote. I thought this was semantically correct, because the backlink is not part of the content.

I did not address any CSS with the formatting of the noteref.

~~~HTML
<section id="reading-410" class="test">
    <h2><span class="test-id">reading-410</span> <span class="test-title">Footnote Reading</span></h2>
    <p class="desc">This tests the useability and functionality of footnotes. The markup includes the semantics that the reference  is to   a note,which could be announced to the reader. The destination could be a footnote or an endnote  and announced to the reader. The link back to the original position has the semantics that it is a backlink and could also be announced to the reader.</p>

<p>To pass this test:</p>
<ul>
<li>Assistive technology is able to detect the reference to the footnote and reach  the content of the footnote.</li>
<li>Assistive technology is able to read the content of the footnote.</li>
<li>The Reading System  provides a mechanism to move back to the original reading position from the footnote, or the backlink is used to return to the original position.</li>
</ul>
   
    <p class="eval">Indicate Pass or Fail.</p>

<p>Please put into the notes if the link to the note was announced, and upon reaching the destination  that it was a footnote. Include if the Reading System included its own mechanism to return to the original location or if the backlink was announced and used to return to the exact location.</p>
<h3>Sample Footnote testing   example</h3>
<p>
     Chief Joseph was a leader of the Nez Perce tribe, who resisted the U.S. government’s attempt to remove them from their ancestral lands in the Wallowa Valley of Oregon. In 1877, after a series of violent encounters with white settlers, Chief Joseph and his people decided to flee the U.S. and seek refuge in Canada, where they hoped to join the Lakota people under Sitting Bull. Along the way, they fought several battles with the U.S. Army, who pursued them relentlessly. Chief Joseph also drove a large herd of horses<a id="backlink-target" href="#ft2f" role="doc-noteref" epub:type="noteref"><sup>1</sup></a>, which he used for transportation and trade. He managed to lead his people across more than 1,000 miles of rugged terrain, reaching the border of Montana and Canada. However, he was surrounded by the army and forced to surrender, ending his remarkable journey of resistance and survival.
   </p>
<p>This is a filler paragraph to show there would be text between the note reference and the footnote.</p>
<aside id="ft2f" role="doc-footnote" epub:type="footnote">
   <p>
     1 The Appaloosa is a spotted horse breed that originated from the selective breeding practices of the Nez Perce tribe in the northwestern U.S. The Nez Perce valued the Appaloosa for its speed, endurance, intelligence, and spiritual power. The name Appaloosa may have derived from the Palouse River or the Palouse tribe, which were associated with the Nez Perce. The Appaloosa is the official state horse of Idaho and a symbol of the region </p>
   <p><a href="#backlink-target" role="doc-backlink">[return to note reference 1 about Chief Joseph]</a></p>
</aside>

<p>End of the footnote testing item.</p>
  </section>
```

**Comment by GeorgeKerscher** [comment]
Closed on the January 9 RS call.
