### ISSUE TITLE
Add tests to Visual Adjustments for MathML

### ISSUE THREAD

**Issue by ways2read** [daisy/epub-accessibility-tests#67]
MathML is well supported across reading systems now, it can be included in the regular test books. In Visual Adjustments it could be inserted before visual-610 Support for SVG, leaving space for any additional image tests.

Proposing 
### Visual-550 Support for MathML
The math expressions below are in MathML format. Check if the math expressions inline and between the paragraphs are displayed correctly. 

*** Here we would have a passage with inline and block MathML ***
 
### Visual-555 Change MathML size
Use the controls available in the application or else in the operating system to change (increase/decrease) the size of the font.  Check if the math expressions given in the previous test also change size in proportion.

### Visual-560 Change MathML colors
Change background and foreground color (may be through reading system feature or through OS settings). Check if the math expressions used in the above test also reflect the changed color settings.

**Comment by avneeshsingh** [comment]
The current text of MathML visual test states:
please verify that you are able to see the portions of the equation highlighted as you navigate the various parts of the equation.

**Comment by ways2read** [comment]
I think I have only seen portions of the equation highlighted as you navigate the various parts of the equation with VoiceOver on macOS. Not on iOS, not with NVDA, and obviously not with TalkBack.

So, as we revise the test books, I think we should omit the highlighting requirement because it is currently not widely supported.

**Comment by ways2read** [comment]
I think I have only seen portions of the equation highlighted as you navigate the various parts of the equation with VoiceOver on macOS. Not on iOS, not with NVDA, and obviously not with TalkBack.

So as we revise the test books, I think we should omit the highlighting requirement because it fails our 50% support principle.

**Comment by clapierre** [comment]
As discussed in the 2/6/24 meeting we will combine all these sub tests into a single one checking size and color adjustments is supported with MathML.
