### ISSUE TITLE
Add a test for supporting language tags

### ISSUE THREAD

**Issue by ways2read** [daisy/epub-accessibility-tests#7]
In non visual reading, and in read aloud, add tests for switching the tts when the language changes.

See [the blog regarding this subject on applevis](https://www.applevis.com/blog/advocacy-apple-ios-ios-apps/reading-bilingual-books-ios-albatross-and-something-should-be-done)

**Comment by prashantverma2014** [comment]
It should be in the fundamental book. If book does not have correct language tags, TTS may not read it at all.

**Comment by avneeshsingh** [comment]
The reasons to have it in fundamental test book are well known. We should document how many reading systems support it, because this is an important criteria to add a test in fundamental test book.
I hope that it is well supported by reading systems. If we have some estimate, it would be good to provide on this thread.

**Comment by GeorgeKerscher** [comment]
Several questions for the non-visual reading test title:
First, is this in the fundamental or the advanced?
Second, are there two tests, one for reading using the down arrow key and one for continuous reading?

**Comment by ways2read** [comment]
If language switching is supported on several test environments then it can go in the fundamental test book. Otherwise, it is an advanced feature until there is wider support. This is the generally applied principle, and this question may also be raised for other revisions in the 2023 milestone.

Maybe we can compile them into a title and check the coverage in one pass?

I don't believe there will be a difference whether reading line by line or using continuous reading.

I think the language change should not be for a complete paragraph but for a phrase within a paragraph.

**Comment by danielweck** [comment]
> I think the language change should not be for a complete paragraph but for a phrase within a paragraph.

Yes, and words too, for example:
```html
<p>in French, the word "book" is <span xml:lang="fr">"livre"</span>.</p>
```

A real-world example is "The Waste Land":

https://idpf.github.io/epub3-samples/30/samples.html#wasteland

https://github.com/IDPF/epub3-samples/blob/main/30/wasteland/EPUB/wasteland-content.xhtml

**Comment by GeorgeKerscher** [comment]
Hi,
 
What passage should I look at? This is a large document.
 
Perhaps something to search for?
 
Bes
tGeorge

**Comment by ways2read** [comment]
I used that poem for the read aloud video. That same passage (a few lines) could work. I will provide this for consideration.

Richard
________________________________

**Comment by GeorgeKerscher** [comment]
!~~~HTML
<section id="reading-1510" class="test">
    <h2><span class="test-id">reading-1510</span> <span class="test-title">TTS Change Languages Automatically</span></h2>
    <p class="desc">Screen readers and other Assistive Technology that use TTS should be able to detect language changes marked in XHTML content. A screen reader should be able to be configured to automatically change the TTS speaking language when it encounters a language change in the XHTML. This test contains English, German, French, and Italian.</p>

<p> Configure your screen reader or other Assistive Technology to automatically change the TTS language. Read the phrases below line by line and continuously. The test passes if the TTS language changes as it encounters the language change.</p>

    <p class="eval">Indicate Pass or Fail.</p>
<h3>Language Change Test</h3>

<p>In English, "Good morning my darling."<br />
  In German, <span xml:lang="de" lang="de">"Guten Morgen, mein Liebling."</span><br />
In french, <span xml:lang="fr" lang="fr">"Bonjour ma chérie."</span><br/>
in Italian, <span xml:lang="it" lang="it">"Buongiorno amore mio."</span>
</p>
<p>End of language change testing.</p>
</section>
~~~

**Comment by gautierchomel** [comment]
[Proposed experimental tests](https://github.com/daisy/transitiontoepub/pull/30) there
