### ISSUE TITLE
Change reading speed test in non-visual book needs revision 

### ISSUE THREAD

**Issue by prashantverma2014** [daisy/epub-accessibility-tests#77]
In the Non-visual test book the test - reading-410 | Change reading speed needs to be removed or updated with more conditions. When testing with a screen reader or Refreshable Braille Display, the test is a pass always. Reading speed adjustment needs to be done in the AT and it is not a Reading System feature.

**Comment by GeorgeKerscher** [comment]
Trying to mark as a 2023 Milestone.

**Comment by GeorgeKerscher** [comment]
This needs to be removed for 2023.

**Comment by GeorgeKerscher** [comment]
Closed on the January 9 meeting.
