### ISSUE TITLE
Add a cover image to the test book(s)

### ISSUE THREAD

**Issue by ways2read** [daisy/epub-accessibility-tests#8]
In order to ingest the test book on certain platforms, a valid cover image must be included. So this should be added to the test book.

**Comment by marisademeglio** [comment]
Just to follow up with what we talked about on the call today -- you can associate an image file with the role `cover-image`, in the package document. This would be what's being shown in a bookshelf view. Then, for a11y, you can make a page in the book containing the cover image along with its text description. It does not seem to me that this description would be available to the bookshelf view, though. There does not seem to be a place for an image description in the package document.

**Comment by danielweck** [comment]
Some reading systems I am familiar with implement the bookshelf / library browser with cover images marked as "decorative", and use other metadata items (title, author, etc) so populate the information for each publication in the catalog display.

In this case, strictly speaking cover images are completely inaccessible to non-sighted / visually-impaired users. Screen readers do not even report their presence in the displayed list / grid of publications.

So I agree that there should be a good practice guideline to include a cover "page" in the reading order / publication spine, where authors can provide descriptive information about the image contents, using conventional HTML methods (e.g. alt, described-by, aria-details etc.)
