### ISSUE TITLE
rephrase the existing TOC hierarchy test for ease of navigation

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#83]
The existing test should be clarified to express ease of navigation. It does not need to be hierarchial, there are other options for the nav doc.

**Comment by marisademeglio** [comment]
For reference -- I think this is the text in question
https://github.com/daisy/epub-accessibility-tests/blob/main/content/epub30-test-0301/EPUB/xhtml/Basic-functionality-tests.xhtml#L46

**Comment by GeorgeKerscher** [comment]
This was reviewed and fixed with the early 2024 revisions.
