### ISSUE TITLE
visual-010 mentions a page list but the book has none

### ISSUE THREAD

**Issue by marisademeglio** [daisy/epub-accessibility-tests#94]
In EPUB-0303, "Visual Adjustments", test `visual-010` [says](https://github.com/daisy/epub-accessibility-tests/blob/revision-visual-adjustments-2023/content/epub30-test-0303/EPUB/xhtml/visual-adjustment-tests.xhtml#L12) 

> The font size change should apply uniformly on all the book content including the Table of Contents, Footnotes, Page List, Notes and Bookmarks.

The book does not have a page list so why mention it in the test?

**Comment by clapierre** [comment]
Here is the original introductory text from test visual-010

> Use the controls available in the application or else in the operating system to change (increase/decrease) the size of the font. The font size change should apply uniformly on all the book content including the Table of Contents, Footnotes, Page List, Notes and Bookmarks.

How should we adjust this. Do we remove Page List, Notes, and Bookmarks?

**Comment by clapierre** [comment]
Should it say book content as well as Reading System UX controls such as Settings, TOC, etc.?

**Comment by ways2read** [comment]
The test visual-410 Magnify the User Interface(UI) covers the UI elements:
> Use the controls available in the application or else in the operating system to magnify the Reading System screen. All aspects of the User Interface such as Menus, Pop-up Windows, Dialog Boxes and Search Box should get magnified uniformly.
So probably, test visual-010 should apply to the content only.
If there is a Table of Contents in the book content, then it would be expected to change size. Not sure why we specifically reference this though.
Page List would not normally appear in the book itself.
Notes and Bookmarks are part of the UI surely, not the content.

**Comment by ways2read** [comment]
Maybe this version better addresses the intent of this test:
> Use the controls available in the application or else in the operating system to change (increase/decrease) the size of the font. The font size change should apply uniformly to all the book content including headings, regular paragraphs, list items, and the text content of tables.

**Comment by ways2read** [comment]
We would expect MathML content to also change size proportionately with the text. This usually happens, but can fail if the reading system changes the MathML to an image. 

Do we address that here or somewhere else in the visual adjustments book?

**Comment by marisademeglio** [comment]
<img width="1670" alt="Screenshot of ebook reader with enlarged font in the main viewport but not the TOC sidebar" src="https://github.com/daisy/epub-accessibility-tests/assets/734730/4b683e30-b10a-4765-a869-48963203230f">
<img width="1153" alt="Screenshot of ebook reader with enlarged font in the main viewport but not the TOC dropdown" src="https://github.com/daisy/epub-accessibility-tests/assets/734730/2ead6acf-9efb-46c1-8631-b963dfb37794">

Here are two examples of reading systems where the TOC does not get enlarged with the rest of the book. Is the TOC list considered a menu and therefore this falls under visual-410? Is that safe to say across reading systems?

**Comment by clapierre** [comment]
Hi @ways2read, I don't think we need to specifically call out MathML here as we would need to add that to the test content, I think that should be a test in the MathML book to be honest.

As for @marisademeglio  comments, that is what I am wondering about, If visual-010 only deals with book content we can ignore the Reading System's UI UX components including TOC. We may need to revisit 410 as that seems to be more appropriate for the Reading Systems components.

**Comment by ways2read** [comment]
@clapierre I thought we were deprecating the math book and including MathML in the relevant test books?

**Comment by ways2read** [comment]
@marisademeglio IMHO the TOCs in those examples are part of the reading app interface. The data in the package file has been parsed and included within a UI element. In the case of Thorium Reader, it is even a subsection within that drop-down menu.

And yes, it is safe to say that the TOC is presented as part of the UI across reading apps, and therefore can be considered along with the required visual adjustments needed for other UI elements such as notes, bookmarks, go to page, etc.

**Comment by clapierre** [comment]
> @clapierre I thought we were deprecating the math book and including MathML in the relevant test books?

I vaguely remember that. So, if that's the case we need a new Issue with which test books will be changed which tests needed to be added so nothing is missed for both Visual and Non-Visual tests for MathML.  I think we may need a separate meeting to figure out how to divide up those MathML tests into the other books.

**Comment by marisademeglio** [comment]
Fixed by https://github.com/daisy/epub-accessibility-tests/commit/3fe63f58ef01f9cda46b068efadb507be5a8de15
